name: build

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs: null

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 17
          msbuild-architecture: x64

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: 'Run build script'
        run: cmd /C build.bat

      - name: "Upload artifacts: OpenSSL (x86_64)"
        uses: actions/upload-artifact@v4
        with:
          name: openssl_x86_64
          path: output/recorder/x86_64/openssl/*

      - name: "Upload artifacts: OpenSSL (arm64)"
        uses: actions/upload-artifact@v4
        with:
          name: openssl_arm64
          path: output/recorder/arm64/openssl/*

      - name: "Upload artifacts: OpenSSL PDBs (x86_64)"
        uses: actions/upload-artifact@v4
        with:
          name: openssl_pdb_x86_64
          path: output/recorder/x86_64/openssl_pdb/*

      - name: "Upload artifacts: OpenSSL PDBs (arm64)"
        uses: actions/upload-artifact@v4
        with:
          name: openssl_pdb_arm64
          path: output/recorder/arm64/openssl_pdb/*
