name: build

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs: null

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@ede762b26a2de8d110bb5a3db4d7e0e080c0e917 # v1.3
        with:
          vs-version: 17
          msbuild-architecture: x64

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: 'Run build script'
        run: cmd /C build.bat

      - name: "Upload artifacts: OpenSSL (x86_64)"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: openssl_x86_64
          path: output/recorder/x86_64/openssl/*

      - name: "Upload artifacts: OpenSSL (arm64)"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: openssl_arm64
          path: output/recorder/arm64/openssl/*

      - name: "Upload artifacts: OpenSSL PDBs (x86_64)"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: openssl_pdb_x86_64
          path: output/recorder/x86_64/openssl_pdb/*

      - name: "Upload artifacts: OpenSSL PDBs (arm64)"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: openssl_pdb_arm64
          path: output/recorder/arm64/openssl_pdb/*
